acf(AirPassengers)
data(AirPassengers)
AP <- AirPassengers
AP.decom <- decompose(AP, "multiplicative")
class(AP.decom$random[7:138])
length(AP)
acf(AP.decom$random[7:138])
sd(AP[7:138])
sd(AP[7:138] - AP.decom$trend[7:138])
sd(AP.decom$random[7:138])